### ISSUE TITLE
Since Ubuntu 25.04 upgrade, Firefox cannot download files

### ISSUE THREAD

**Issue by Christopher-Hayes** [canonical/desktop-security-center#124]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I just upgraded to Ubuntu 25.04 and despite my Firefox Snap having ALL of the permissions, as well as having READ + WRITE permissions to my /Downloads folder, it cannot download files. Every download is failing.

I'm seeing errors like this:

![Image](https://github.com/user-attachments/assets/70ff4936-4875-493a-ac08-967703642437)

My `about:config` has `browser.download.start_downloads_in_tmp_dir` **disabled**, so the permission issue should only be related to the ~/Downloads folders.

**Firefox should have access to the ~/Downloads**, and downloads worked fine on `Ubuntu 24.10`, but after the `25.04` upgrade, they no longer work.

![Image](https://github.com/user-attachments/assets/3655b660-106f-4b61-9d8d-c98cce860ad4)

<details>
<summary>
Firefox has ALL the permissions—
</summary>

![Image](https://github.com/user-attachments/assets/0351a359-1432-406a-a44e-94f50bffdbbf)

</details>

### Steps to reproduce the behavior

1. Open Firefox.
2. Go to any site with a download link, and attempt to download a file.
3. The download will fail with an error like "<file download path> could not be saved, because you cannot change the contents of that folder. Change the folder properties and try again, or try saving in a different location."

This happened for every download across several different sites.

### Expected behavior

1. Open Firefox.
2. Go to any site with a download link, and attempt to download a file.
3. The file should download without an error in the Downloads folder.

### Ubuntu release

Other (specify in the last field)

### What architecture are you using?

amd64

### System info

```yaml
6.14.0-15-generic #15-Ubuntu SMP PREEMPT_DYNAMIC Sun Apr  6 15:05:05 UTC 2025
name:      snapd
summary:   Daemon and tooling that enable snap packages
publisher: Canonical✓
store-url: https://snapcraft.io/snapd
contact:   https://github.com/snapcore/snapd/issues
license:   GPL-3.0
description: |
  Install, configure, refresh and remove snap packages. Snaps are
  'universal' packages that work across many different Linux systems,
  enabling secure distribution of the latest apps and utilities for
  cloud, servers, desktops and the internet of things.

  Start with 'snap list' to see installed snaps.
type:         snapd
snap-id:      PMrrV4ml8uWuEUDBT8dSGnKUYbevVhc4
tracking:     latest/stable
refresh-date: 18 days ago, at 15:57 EDT
channels:
  latest/stable:    2.68.4            2025-04-30 (24505) 53MB -
  latest/candidate: 2.68.4            2025-04-15 (24505) 53MB -
  latest/beta:      2.68.4            2025-04-06 (24505) 53MB -
  latest/edge:      2.69+g132.72c072d 2025-05-15 (24703) 51MB -
installed:          2.68.4                       (24505) 53MB snapd
---
name:      prompting-client
summary:   Prompting Client
publisher: Canonical✓
store-url: https://snapcraft.io/prompting-client
license:   GPL-3.0
description: |
  The official client for snap apparmor prompting.
commands:
  - prompting-client.echo
  - prompting-client.logging-level
  - prompting-client.scripted
services:
  prompting-client.daemon: simple, enabled, inactive
snap-id:      aoc5lfC8aUd2VL8VpvynUJJhGXp5K6Dj
tracking:     1/stable/ubuntu-25.04
refresh-date: 36 days ago, at 07:26 EDT
channels:
  latest/stable:    0+git.d542a5d 2025-04-10 (104) 15MB -
  latest/candidate: ↑
  latest/beta:      ↑
  latest/edge:      0+git.eb0a0f8 2025-04-24 (108) 15MB -
  1/stable:         0+git.d542a5d 2025-04-10 (104) 15MB -
  1/candidate:      ↑
  1/beta:           ↑
  1/edge:           0+git.eb0a0f8 2025-04-24 (108) 15MB -
installed:          0+git.d542a5d            (104) 15MB -
---
name:    desktop-security-center
summary: The desktop Security Center will provide easy-to-access security
  features in Ubuntu.
publisher: Canonical✓
store-url: https://snapcraft.io/desktop-security-center
license:   GPL-3.0
description: |
  The desktop Security Center will provide easy-to-access security features
  in Ubuntu.

  In this first release, users can enable experimental application
  permissions prompting for fine-grained control over how apps access files
  and folders.

  Permissions management requires the supporting `prompting-client` snap to
  be installed alongside; this is included by default on Ubuntu 24.10 and
  future releases.

  New features will be added in coming releases.
commands:
  - desktop-security-center
snap-id:      FppXWunWzuRT2NUT9CwoBPNJNZBYOCk0
tracking:     1/stable/ubuntu-25.04
refresh-date: 36 days ago, at 07:26 EDT
channels:
  latest/stable:    0+git.f7ad73a 2025-04-10 (59) 12MB -
  latest/candidate: ↑
  latest/beta:      ↑
  latest/edge:      0+git.7b03e4c 2025-04-24 (62) 12MB -
  1/stable:         0+git.f7ad73a 2025-04-10 (59) 12MB -
  1/candidate:      ↑
  1/beta:           ↑
  1/edge:           0+git.7b03e4c 2025-04-24 (62) 12MB -
installed:          0+git.f7ad73a            (59) 12MB -
```

### App or apps where you encountered the issue

Firefox 138.0 (64-bit)

### Additional context

Ubuntu release: `Ubuntu 25.04`
Windowing System: `Wayland`

**Sidenote:** Due to limitations with Firefox Snap + Wayland + nvidia, I am forced to install the /latest/candidate/core24 firefox snap release or GPU acceleration does not work.

My `~/Downloads` folder permissions look like:

```
drwxr-xr-x chris chris
```

The current workaround is to disable <kbd>Require apps to ask for system permissions</kbd> in the **Security Center**.

Possibly related to #123; however, I do not see any type of permission popup since Firefox should already have the access it needs.
